#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Mon Nov  3 09:33:41 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class Ventana4(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0, informacion2="", subtotal2=0):
        # begin wxGlade: Ventana4.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((764, 680))
        self.SetTitle("frame_3")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(81, 9, 100))

        #Variables de instancia de la Ventana4
        self.infoTaquilla = informacion
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal
        self.subtotalDulceria = subtotal2
        self.total= self.subtotalTaquilla + self.subtotalDulceria

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(9, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logoticket.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_1, 0, wx.ALIGN_BOTTOM, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(30, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logoticket.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(30, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTaquilla.SetForegroundColour(wx.Colour(255, 255, 255))
        lbTaquilla.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Wide Latin"))
        grid_sizer_1.Add(lbTaquilla, 0, wx.ALIGN_CENTER, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"SubTotal: ${self.subtotalTaquilla}")
        lbSubtotalTaquilla.SetForegroundColour(wx.Colour(74, 179, 255))
        lbSubtotalTaquilla.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Source Serif Pro"))
        grid_sizer_1.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(30, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbDulceria.SetForegroundColour(wx.Colour(255, 255, 255))
        lbDulceria.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Wide Latin"))
        grid_sizer_1.Add(lbDulceria, 0, wx.ALIGN_CENTER, 0)

        lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"SubTotal: ${self.subtotalDulceria}")
        lbSubtotalDulceria.SetForegroundColour(wx.Colour(74, 179, 255))
        lbSubtotalDulceria.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Source Serif Pro"))
        grid_sizer_1.Add(lbSubtotalDulceria, 0, 0, 0)

        self.lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"Total: ${self.total}")
        self.lbTotal.SetForegroundColour(wx.Colour(255, 37, 37))
        self.lbTotal.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Modern No. 20"))
        grid_sizer_1.Add(self.lbTotal, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetMinSize((160, 43))
        self.btnCancelar.SetBitmap(wx.Bitmap("E:\\CinePlusEmiliCampos3A\\BotonCancelar2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        self.btnFinalizar.SetMinSize((160, 43))
        self.btnFinalizar.SetBitmap(wx.Bitmap("E:\\CinePlusEmiliCampos3A\\BotonFinalizar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        #Finalizar el programa
        self.Close()
        wx.Exit()
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        mensaje = wx.MessageDialog(self,
        f"Venta Finalizada.", style=wx.OK | wx.ICON_INFORMATION)

        respuesta = mensaje.ShowModal()
        mensaje.Destroy() #Cerramos el dialogo

        if respuesta == wx.ID_OK:
            v2= Ventana2(self)
            v2.Show()
            self.Hide()
        event.Skip()

# end of class Ventana4
class Ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((897, 778))
        self.SetTitle("frame_2")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(7, 19, 125))

        #Variables de instancia Ventana 3
        self.infoDulceria = ""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bmLogo1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("LogoDulceria2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmLogo1, 0, 0, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        lbDulceria.SetForegroundColour(wx.Colour(255, 255, 255))
        lbDulceria.SetFont(wx.Font(20, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_1.Add(lbDulceria, 0, wx.ALIGN_CENTER, 0)

        bmLogo2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("LogoDulceria2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmLogo2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)

        lbCombos = wx.StaticText(self.panel_1, wx.ID_ANY, "Combos:")
        lbCombos.SetForegroundColour(wx.Colour(255, 255, 255))
        lbCombos.SetFont(wx.Font(15, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Calisto MT"))
        sizer_1.Add(lbCombos, 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboB.SetMinSize((66, 35))
        self.spComboB.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sylfaen"))
        grid_sizer_3.Add(self.spComboB, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bell MT"))
        grid_sizer_5.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch\nRefresco ch")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_5.Add(label_2, 0, 0, 0)

        grid_sizer_24 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_24, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenPalomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_24.Add(bitmap_3, 0, wx.ALIGN_CENTER, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_24.Add(bitmap_4, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboC.SetMinSize((66, 35))
        self.spComboC.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sylfaen"))
        grid_sizer_4.Add(self.spComboC, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        label_4.SetMinSize((125, 39))
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(15, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_6.Add(label_4, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas md\n2 Refrescos md")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_6.Add(label_6, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_26 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_4.Add(grid_sizer_26, 1, wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenPalomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_26.Add(bitmap_5, 0, wx.ALIGN_CENTER, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_26.Add(bitmap_6, 0, wx.ALIGN_CENTER, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_26.Add(bitmap_7, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboF.SetMinSize((66, 35))
        self.spComboF.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sylfaen"))
        grid_sizer_8.Add(self.spComboF, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_9 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar")
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bell MT"))
        grid_sizer_9.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G\n3 Refrescos G\n1 Dulce")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_9.Add(label_5, 0, 0, 0)

        grid_sizer_25 = wx.GridSizer(1, 5, 0, 0)
        grid_sizer_8.Add(grid_sizer_25, 1, wx.EXPAND, 0)

        bitmap_8 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenPalomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_25.Add(bitmap_8, 0, wx.ALIGN_CENTER, 0)

        bitmap_9 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_25.Add(bitmap_9, 0, wx.ALIGN_CENTER, 0)

        bitmap_10 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_25.Add(bitmap_10, 0, wx.ALIGN_CENTER, 0)

        bitmap_11 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_25.Add(bitmap_11, 0, wx.ALIGN_CENTER, 0)

        bitmap_12 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenDulce.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_25.Add(bitmap_12, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7.Add((0, 0), 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenPalomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(bitmap_1, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_12 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_7.SetForegroundColour(wx.Colour(255, 255, 255))
        label_7.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bell MT"))
        grid_sizer_12.Add(label_7, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_13 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasCh.SetMinSize((46, 30))
        self.spPalomitasCh.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_13.Add(self.spPalomitasCh, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        label_8.SetForegroundColour(wx.Colour(255, 255, 255))
        label_8.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_13.Add(label_8, 0, 0, 0)

        grid_sizer_14 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_12.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasMd.SetMinSize((46, 30))
        self.spPalomitasMd.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_14.Add(self.spPalomitasMd, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_14.Add(label_9, 0, 0, 0)

        grid_sizer_15 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_12.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasG.SetMinSize((46, 30))
        self.spPalomitasG.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_15.Add(self.spPalomitasG, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        label_10.SetForegroundColour(wx.Colour(255, 255, 255))
        label_10.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_15.Add(label_10, 0, 0, 0)

        grid_sizer_16 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_10.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("ImagenRefresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_16.Add(bitmap_2, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_17 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_16.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_11.SetForegroundColour(wx.Colour(255, 255, 255))
        label_11.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bell MT"))
        grid_sizer_17.Add(label_11, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_18 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_17.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_12.SetForegroundColour(wx.Colour(255, 255, 255))
        label_12.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_18.Add(label_12, 0, wx.ALIGN_CENTER, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_13.SetForegroundColour(wx.Colour(255, 255, 255))
        label_13.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_18.Add(label_13, 0, wx.ALIGN_CENTER, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_14.SetForegroundColour(wx.Colour(255, 255, 255))
        label_14.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_18.Add(label_14, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_19 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_17.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["CHICO", "MEDIANO", "GRANDE"], style=wx.CB_DROPDOWN)
        self.cmbTamano.SetMinSize((45, 23))
        grid_sizer_19.Add(self.cmbTamano, 0, wx.ALIGN_CENTER, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["COCA-COLA", "PEPSI", "FANTA", "JARRITO-DE-UVA"], style=wx.CB_DROPDOWN)
        self.cmbSabor.SetMinSize((45, 23))
        grid_sizer_19.Add(self.cmbSabor, 0, wx.ALIGN_CENTER, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidad.SetMinSize((46, 30))
        self.spCantidad.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_19.Add(self.spCantidad, 0, wx.ALIGN_CENTER, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar.SetMinSize((60, 30))
        grid_sizer_19.Add(self.btnAgregar, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_20 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        grid_sizer_21 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_20.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos agregados:")
        label_15.SetMinSize((199, 26))
        label_15.SetForegroundColour(wx.Colour(255, 255, 255))
        label_15.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_21.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "- - -")
        self.lbProductosAgregados.SetForegroundColour(wx.Colour(255, 255, 255))
        self.lbProductosAgregados.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_21.Add(self.lbProductosAgregados, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_22 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_20.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria:")
        label_17.SetForegroundColour(wx.Colour(255, 255, 255))
        label_17.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Bell MT"))
        grid_sizer_22.Add(label_17, 0, wx.ALIGN_CENTER, 0)

        self.lbSubTotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        self.lbSubTotal.SetForegroundColour(wx.Colour(203, 0, 12))
        self.lbSubTotal.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Tahoma"))
        grid_sizer_22.Add(self.lbSubTotal, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_23 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((105, 43))
        self.btnLimpiar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnLimpiar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnLimpiar.SetBitmap(wx.Bitmap("ImagenLimpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_23.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((105, 43))
        self.btnSiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnSiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnSiguiente.SetBitmap(wx.Bitmap("ImagenSiguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_23.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Basicos \n "
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularComboCuates(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Cuates \n "
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularComboFamiliar(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*200
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Familiar \n "
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularPalomitasCh(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*30
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Chicas \n "
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularPalomitasMd(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*50
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Medianas \n "
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularPalomitasG(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Grandes \n "
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def agregarRefresco(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()
        subtotalrefresco=0
        
        if tamanyo == "CHICO":
            subtotalrefresco=numero*25
        elif tamanyo == "MEDIANO":
            subtotalrefresco=numero*40
        elif tamanyo == "GRANDE":
            subtotalrefresco=numero*60

        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbSubTotal.SetLabel(f"${self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero} Refresco: {sabor} tamaño {tamanyo}\n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)

        event.Skip()

    def limpiarD(self):
        #Limpiamos las variables de instancia
        self.subtotalDulceria=0
        self.infoDulceria=""

        #Limpiamos los controles
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("---")
        self.lbSubTotal.SetLabel("$00.00")

    def limpiarDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        event.Skip()
    def siguienteDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmacion de Dulceria. \n"
        f"¿Esta seguro que desea adquirir?\n\n{self.infoDulceria}\n"
        f"Subtotal Dulceria: ${self.subtotalDulceria}",
        "Dulceria",style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #Cerramos el dialogo

        if respuesta == wx.ID_YES:
            v4 = Ventana4(self, informacion=self.infoTaquilla,
                          subtotal=self.subtotalTaquilla,
                          informacion2=self.infoDulceria,
                          subtotal2=self.subtotalDulceria)
            v4.Show()
            self.limpiarD()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD()

        event.Skip()
# end of class Ventana3

class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((542, 649))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 186))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bmLogo1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("LogoCinePlusej2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmLogo1, 0, 0, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        lbTaquilla.SetForegroundColour(wx.Colour(255, 255, 255))
        lbTaquilla.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Text"))
        grid_sizer_1.Add(lbTaquilla, 0, wx.ALIGN_CENTER, 0)

        bmLogo2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("LogoCinePlusej2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmLogo2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        lbPelicula.SetForegroundColour(wx.Colour(255, 255, 255))
        lbPelicula.SetFont(wx.Font(20, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_4.Add(lbPelicula, 0, wx.ALIGN_CENTER, 0)

        lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        lbSala.SetForegroundColour(wx.Colour(255, 255, 255))
        lbSala.SetFont(wx.Font(20, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_4.Add(lbSala, 0, wx.ALIGN_CENTER, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        lbHorario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbHorario.SetFont(wx.Font(20, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_4.Add(lbHorario, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Coraline y la puerta secreta", "El cadaver de la novia", "Alicia en el pais de las maravillas", "", ""], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetMinSize((150, 40))
        self.cmbPelicula.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "SimSun"))
        grid_sizer_5.Add(self.cmbPelicula, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbVerSala = wx.StaticText(self.panel_1, wx.ID_ANY, "     - -")
        self.lbVerSala.SetMinSize((100, 50))
        self.lbVerSala.SetForegroundColour(wx.Colour(255, 255, 255))
        self.lbVerSala.SetFont(wx.Font(20, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Elephant"))
        grid_sizer_5.Add(self.lbVerSala, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_6 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario1.SetMinSize((112, 40))
        self.rbHorario1.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario1.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Heading"))
        grid_sizer_6.Add(self.rbHorario1, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetMinSize((112, 40))
        self.rbHorario2.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario2.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Banner"))
        grid_sizer_6.Add(self.rbHorario2, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario3.SetMinSize((112, 40))
        self.rbHorario3.SetForegroundColour(wx.Colour(255, 255, 255))
        self.rbHorario3.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Banner"))
        grid_sizer_6.Add(self.rbHorario3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\CinePlusEmiliCampos3A\\Coraline y la puerta secreta.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(self.bmPelicula, 0, wx.ALIGN_CENTER, 0)

        lbBoletos = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        lbBoletos.SetForegroundColour(wx.Colour(255, 255, 255))
        lbBoletos.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Text"))
        sizer_1.Add(lbBoletos, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        lbAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos $80 :")
        lbAdultos.SetForegroundColour(wx.Colour(255, 255, 255))
        lbAdultos.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Source Sans Pro"))
        grid_sizer_2.Add(lbAdultos, 0, wx.ALIGN_CENTER, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        grid_sizer_2.Add(self.tfAdultos, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        lbMenores = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores $70 :")
        lbMenores.SetForegroundColour(wx.Colour(255, 255, 255))
        lbMenores.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Source Sans Pro"))
        grid_sizer_7.Add(lbMenores, 0, wx.ALIGN_CENTER, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        grid_sizer_7.Add(self.tfMenores, 0, wx.ALIGN_CENTER, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Sub Total: $")
        self.lbSubtotal.SetForegroundColour(wx.Colour(255, 255, 255))
        self.lbSubtotal.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Source Sans Pro"))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((155, 45))
        self.btnLimpiar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnLimpiar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnLimpiar.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Trebuchet MS"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("ImagenLimpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((155, 45))
        self.btnSiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnSiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnSiguiente.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Trebuchet MS"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("ImagenSiguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        #print(f"ruta: {ruta}")
        bitmap = wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        Pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""

        print(f"Pelicula selecionada: {Pelicula}")

        if Pelicula == "Coraline y la puerta secreta":
            imagen="Coraline y la puerta secreta.jpg"
            sala="1"
            horario1="14:00"
            horario2="17:00"
            horario3="20:00"

        elif Pelicula == "El cadaver de la novia":
            imagen="El cadaver de la novia.jpg"
            sala="2"
            horario1="13:30"
            horario2="16:30"
            horario3="19:30"

        elif Pelicula == "Alicia en el pais de las maravillas":
            imagen="Alicia en el pais de las maravillas.png"
            sala="3"
            horario1="15:00"
            horario2="18:00"
            horario3="21:00"

        self.cargar_imagen(imagen)
        self.lbVerSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {Pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a
            self.lbSubtotal.SetLabel(f"subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Porfavor ingresa un numero valido", "error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b
            self.lbSubtotal.SetLabel(f"subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("Porfavor ingresa un numero valido", "error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    #Creacion de la funcion limpiar para la Ventana 2
    def limpiarValores_Campos(self):

        #Limpiar Variables de Instancia
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        #Limpiar campos
        self.cargar_imagen("LogoCinePlusej2.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPelicula.SetSelection(wx.NOT_FOUND)
        self.lbVerSala.SetLabel("----")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbSubtotal.SetLabel("0")


    def limpiarTaquilla(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion} \n Adultos: {self.adultos} \n Menores de 12 años: {self.menores}"
        self.informacion = f"{self.informacion} \n SubTotal: {self.subtotal}"

        pregunta = wx.MessageDialog(
        self,
        f"Confirmacion de taquilla \n"
        f"¿Estas seguro que deseas adquirir?\n\n{self.informacion}"
        "Taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #cerramos el dialogo

        if respuesta == wx.ID_YES:
            print(f"venta de taquilla realizada \n {self.informacion}")
            v3 = Ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos() 
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos() 
             
        event.Skip()

# end of class Ventana2

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((404, 466))
        self.SetTitle("Inicio de sesion - Cine Plus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("IMAGENCINEPLUS.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((384, 30))
        lbTitulo.SetForegroundColour(wx.Colour(185, 143, 255))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lblogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./IMAGENCINEPLUS.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lblogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetMinSize((44, 30))
        lbUsuario.SetForegroundColour(wx.Colour(201, 148, 255))
        lbUsuario.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbUsuario, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetForegroundColour(wx.Colour(0, 0, 0))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((64, 30))
        lbClave.SetForegroundColour(wx.Colour(189, 159, 255))
        lbClave.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbClave, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue ( )
        clave = self.tfClave.GetValue ( )

        if nombre == "Millie" and clave == "123":
            print(f"¡Bienvenida, {nombre}! Acceso autorizado.")
            v2 = Ventana2(self)
            v2.Show()
            self.Hide()
        else:
            print("Acceso denegado. Usuario o clave incorrectos.")

        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

# end of class Ventana1

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame_1 = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_1)
        self.frame_1.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
